OTP24
josefs/Gradualizer pull request #335
Opened 2021-06-06 17:53 UTC by josefs

Use OTP 24 in travis and use native implementation of maps:merge_with when available.

2021-06-06 17:59 UTC, josefs commented
Travis doesn't support the latest version of OTP yet. I didn't check before submitting the PR. Oh well, I guess I'll just leave this one here for the time being.

2021-06-07 11:58 UTC, zuiderkwast reviewed
Looks good. You can merge one of the two commits if you want.

2021-06-07 11:58 UTC, zuiderkwast commented on src/gradualizer_lib.erl
> +    maps:merge_with(F, M1, M2).
Nice! Do you know who added this to OTP?

2021-06-07 12:01 UTC, zuiderkwast requested changes

2021-06-07 12:01 UTC, zuiderkwast commented on src/gradualizer_lib.erl
> +-if(?OTP_RELEASE >= "24").
Oops, ?OTP_RELEASE is an integer.

```suggestion
-if(?OTP_RELEASE >= 24).
```

2022-04-03 03:22 UTC, zuiderkwast approved these changes

2022-08-29 18:00 UTC, merged

2022-08-29 19:37 UTC, zuiderkwast commented on src/gradualizer_lib.erl
> +-else.
We could have used `-import(maps, [merge_with/3]).` instead. Doesn't matter though.